"""Pydantic models module."""

from app.models.auth import AuthenticatedUser, JWTClaims
from app.models.job import (
    JobDetailResponse,
    JobErrorDetail,
    JobErrorResponse,
    JobListItem,
    JobQueueStats,
    JobResponse,
    JobsListResponse,
    JobStageHistory,
    JobStatsResponse,
    JobStatus,
    JobType,
    ProcessingJob,
    ProcessingJobCreate,
    ProcessingJobUpdate,
    ProcessingJobWithHistory,
    StageStatus,
)
from app.models.entity import (
    EntitiesListResponse,
    EntityEdge,
    EntityEdgeCreate,
    EntityErrorDetail,
    EntityErrorResponse,
    EntityExtractionResult,
    EntityListItem,
    EntityMention,
    EntityMentionCreate,
    EntityMentionsResponse,
    EntityNode,
    EntityNodeCreate,
    EntityNodeWithRelations,
    EntityResponse,
    EntityType,
    ExtractedEntity,
    ExtractedEntityMention,
    ExtractedRelationship,
    RelationshipType,
)
from app.models.matter import (
    Matter,
    MatterCreate,
    MatterInvite,
    MatterListMeta,
    MatterListResponse,
    MatterMember,
    MatterMemberUpdate,
    MatterResponse,
    MatterRole,
    MatterStatus,
    MatterUpdate,
    MatterWithMembers,
    MatterWithMembersResponse,
    MemberListResponse,
    MemberResponse,
)
from app.models.rerank import (
    RerankRequest,
    RerankedSearchMeta,
    RerankedSearchResponse,
    RerankedSearchResultItem,
)

__all__ = [
    # Auth models
    "AuthenticatedUser",
    "JWTClaims",
    # Job models
    "JobDetailResponse",
    "JobErrorDetail",
    "JobErrorResponse",
    "JobListItem",
    "JobQueueStats",
    "JobResponse",
    "JobsListResponse",
    "JobStageHistory",
    "JobStatsResponse",
    "JobStatus",
    "JobType",
    "ProcessingJob",
    "ProcessingJobCreate",
    "ProcessingJobUpdate",
    "ProcessingJobWithHistory",
    "StageStatus",
    # Entity models
    "EntitiesListResponse",
    "EntityEdge",
    "EntityEdgeCreate",
    "EntityErrorDetail",
    "EntityErrorResponse",
    "EntityExtractionResult",
    "EntityListItem",
    "EntityMention",
    "EntityMentionCreate",
    "EntityMentionsResponse",
    "EntityNode",
    "EntityNodeCreate",
    "EntityNodeWithRelations",
    "EntityResponse",
    "EntityType",
    "ExtractedEntity",
    "ExtractedEntityMention",
    "ExtractedRelationship",
    "RelationshipType",
    # Matter models
    "Matter",
    "MatterCreate",
    "MatterInvite",
    "MatterListMeta",
    "MatterListResponse",
    "MatterMember",
    "MatterMemberUpdate",
    "MatterResponse",
    "MatterRole",
    "MatterStatus",
    "MatterUpdate",
    "MatterWithMembers",
    "MatterWithMembersResponse",
    "MemberListResponse",
    "MemberResponse",
    # Rerank models
    "RerankRequest",
    "RerankedSearchMeta",
    "RerankedSearchResponse",
    "RerankedSearchResultItem",
]
