"""Pydantic models module."""

from app.models.auth import AuthenticatedUser, JWTClaims
from app.models.job import (
    JobDetailResponse,
    JobErrorDetail,
    JobErrorResponse,
    JobListItem,
    JobQueueStats,
    JobResponse,
    JobsListResponse,
    JobStageHistory,
    JobStatsResponse,
    JobStatus,
    JobType,
    ProcessingJob,
    ProcessingJobCreate,
    ProcessingJobUpdate,
    ProcessingJobWithHistory,
    StageStatus,
)
from app.models.entity import (
    EntitiesListResponse,
    EntityEdge,
    EntityEdgeCreate,
    EntityErrorDetail,
    EntityErrorResponse,
    EntityExtractionResult,
    EntityListItem,
    EntityMention,
    EntityMentionCreate,
    EntityMentionsResponse,
    EntityNode,
    EntityNodeCreate,
    EntityNodeWithRelations,
    EntityResponse,
    EntityType,
    ExtractedEntity,
    ExtractedEntityMention,
    ExtractedRelationship,
    RelationshipType,
)
from app.models.matter import (
    Matter,
    MatterCreate,
    MatterInvite,
    MatterListMeta,
    MatterListResponse,
    MatterMember,
    MatterMemberUpdate,
    MatterResponse,
    MatterRole,
    MatterStatus,
    MatterUpdate,
    MatterWithMembers,
    MatterWithMembersResponse,
    MemberListResponse,
    MemberResponse,
)
from app.models.rerank import (
    RerankRequest,
    RerankedSearchMeta,
    RerankedSearchResponse,
    RerankedSearchResultItem,
)
from app.models.citation import (
    ActDiscoveryResponse,
    ActDiscoverySummary,
    ActResolution,
    ActResolutionCreate,
    ActResolutionStatus,
    ActResolutionUpdate,
    Citation,
    CitationCreate,
    CitationErrorDetail,
    CitationErrorResponse,
    CitationExtractionResult,
    CitationListItem,
    CitationResponse,
    CitationsListResponse,
    CitationSummaryItem,
    CitationSummaryResponse,
    CitationUpdate,
    ExtractedCitation,
    UserAction,
    VerificationStatus,
)
from app.models.orchestrator import (
    ENGINE_PRIORITY,
    LOW_CONFIDENCE_THRESHOLD,
    EngineType,
    IntentAnalysisCost,
    IntentAnalysisErrorDetail,
    IntentAnalysisErrorResponse,
    IntentAnalysisRequest,
    IntentAnalysisResponse,
    IntentAnalysisResult,
    IntentClassification,
    QueryIntent,
    # Story 6-2: Execution models
    EngineExecutionRequest,
    EngineExecutionResult,
    ExecutionPlan,
    OrchestratorResponse,
    OrchestratorResult,
    SourceReference,
    # Story 6-3: Audit Trail models
    FindingAuditEntry,
    LLMCostEntry,
    QueryAuditEntry,
    QueryAuditRecord,
)
from app.models.memory import (
    # Story 7-1: Session Memory models
    SessionContext,
    SessionEntityMention,
    SessionMessage,
)
from app.models.safety import (
    # Story 8-1: Safety Layer models
    GuardrailCheck,
    GuardrailPattern,
    ViolationType,
    # Story 8-2: Subtle Violation Detection models
    SafetyCheckResult,
    SubtleViolationCheck,
    # Story 8-3: Language Policing models
    LanguagePolicingResult,
    QuotePreservation,
    ReplacementRecord,
)
from app.models.verification import (
    # Story 8-4: Verification models
    BulkVerificationRequest,
    BulkVerificationResponse,
    ExportBlockingFinding,
    ExportEligibilityResult,
    FindingVerification,
    FindingVerificationCreate,
    FindingVerificationUpdate,
    VerificationDecision,
    VerificationListResponse,
    VerificationQueueItem,
    VerificationQueueResponse,
    VerificationRequirement,
    VerificationResponse,
    VerificationStats,
    VerificationStatsResponse,
)

__all__ = [
    # Auth models
    "AuthenticatedUser",
    "JWTClaims",
    # Job models
    "JobDetailResponse",
    "JobErrorDetail",
    "JobErrorResponse",
    "JobListItem",
    "JobQueueStats",
    "JobResponse",
    "JobsListResponse",
    "JobStageHistory",
    "JobStatsResponse",
    "JobStatus",
    "JobType",
    "ProcessingJob",
    "ProcessingJobCreate",
    "ProcessingJobUpdate",
    "ProcessingJobWithHistory",
    "StageStatus",
    # Entity models
    "EntitiesListResponse",
    "EntityEdge",
    "EntityEdgeCreate",
    "EntityErrorDetail",
    "EntityErrorResponse",
    "EntityExtractionResult",
    "EntityListItem",
    "EntityMention",
    "EntityMentionCreate",
    "EntityMentionsResponse",
    "EntityNode",
    "EntityNodeCreate",
    "EntityNodeWithRelations",
    "EntityResponse",
    "EntityType",
    "ExtractedEntity",
    "ExtractedEntityMention",
    "ExtractedRelationship",
    "RelationshipType",
    # Matter models
    "Matter",
    "MatterCreate",
    "MatterInvite",
    "MatterListMeta",
    "MatterListResponse",
    "MatterMember",
    "MatterMemberUpdate",
    "MatterResponse",
    "MatterRole",
    "MatterStatus",
    "MatterUpdate",
    "MatterWithMembers",
    "MatterWithMembersResponse",
    "MemberListResponse",
    "MemberResponse",
    # Rerank models
    "RerankRequest",
    "RerankedSearchMeta",
    "RerankedSearchResponse",
    "RerankedSearchResultItem",
    # Citation models
    "ActDiscoveryResponse",
    "ActDiscoverySummary",
    "ActResolution",
    "ActResolutionCreate",
    "ActResolutionStatus",
    "ActResolutionUpdate",
    "Citation",
    "CitationCreate",
    "CitationErrorDetail",
    "CitationErrorResponse",
    "CitationExtractionResult",
    "CitationListItem",
    "CitationResponse",
    "CitationsListResponse",
    "CitationSummaryItem",
    "CitationSummaryResponse",
    "CitationUpdate",
    "ExtractedCitation",
    "UserAction",
    "VerificationStatus",
    # Orchestrator models (Story 6-1)
    "ENGINE_PRIORITY",
    "LOW_CONFIDENCE_THRESHOLD",
    "EngineType",
    "IntentAnalysisCost",
    "IntentAnalysisErrorDetail",
    "IntentAnalysisErrorResponse",
    "IntentAnalysisRequest",
    "IntentAnalysisResponse",
    "IntentAnalysisResult",
    "IntentClassification",
    "QueryIntent",
    # Orchestrator models (Story 6-2)
    "EngineExecutionRequest",
    "EngineExecutionResult",
    "ExecutionPlan",
    "OrchestratorResponse",
    "OrchestratorResult",
    "SourceReference",
    # Orchestrator models (Story 6-3)
    "FindingAuditEntry",
    "LLMCostEntry",
    "QueryAuditEntry",
    "QueryAuditRecord",
    # Memory models (Story 7-1)
    "SessionContext",
    "SessionEntityMention",
    "SessionMessage",
    # Safety models (Story 8-1)
    "GuardrailCheck",
    "GuardrailPattern",
    "ViolationType",
    # Safety models (Story 8-2)
    "SafetyCheckResult",
    "SubtleViolationCheck",
    # Language Policing models (Story 8-3)
    "LanguagePolicingResult",
    "QuotePreservation",
    "ReplacementRecord",
    # Verification models (Story 8-4)
    "BulkVerificationRequest",
    "BulkVerificationResponse",
    "ExportBlockingFinding",
    "ExportEligibilityResult",
    "FindingVerification",
    "FindingVerificationCreate",
    "FindingVerificationUpdate",
    "VerificationDecision",
    "VerificationListResponse",
    "VerificationQueueItem",
    "VerificationQueueResponse",
    "VerificationRequirement",
    "VerificationResponse",
    "VerificationStats",
    "VerificationStatsResponse",
]
