import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
import { render, screen, waitFor, act } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { MatterNameInput } from './MatterNameInput';

describe('MatterNameInput', () => {
  beforeEach(() => {
    vi.useFakeTimers({ shouldAdvanceTime: true });
  });

  afterEach(() => {
    vi.runOnlyPendingTimers();
    vi.useRealTimers();
  });

  describe('rendering', () => {
    it('renders input with label', () => {
      render(<MatterNameInput value="" onChange={vi.fn()} />);

      expect(screen.getByLabelText(/matter name/i)).toBeInTheDocument();
    });

    it('renders with provided value', () => {
      render(<MatterNameInput value="Test Matter" onChange={vi.fn()} />);

      expect(screen.getByRole('textbox')).toHaveValue('Test Matter');
    });

    it('renders character count', () => {
      render(<MatterNameInput value="Hello" onChange={vi.fn()} />);

      expect(screen.getByText('5/100')).toBeInTheDocument();
    });

    it('shows auto-generated hint when isAutoGenerated is true', () => {
      render(<MatterNameInput value="Test" onChange={vi.fn()} isAutoGenerated={true} />);

      expect(screen.getByText(/auto-generated from first file/i)).toBeInTheDocument();
    });

    it('hides auto-generated hint when isAutoGenerated is false', () => {
      render(<MatterNameInput value="Test" onChange={vi.fn()} isAutoGenerated={false} />);

      expect(screen.queryByText(/auto-generated from first file/i)).not.toBeInTheDocument();
    });
  });

  describe('input behavior', () => {
    it('updates local value on typing', async () => {
      const user = userEvent.setup({ advanceTimers: vi.advanceTimersByTime });
      const onChange = vi.fn();
      render(<MatterNameInput value="" onChange={onChange} />);

      const input = screen.getByRole('textbox');
      await user.type(input, 'New Matter');

      // Flush pending timers
      await act(async () => {
        vi.advanceTimersByTime(300);
      });

      expect(input).toHaveValue('New Matter');
    });

    it('calls onChange after debounce', async () => {
      const user = userEvent.setup({ advanceTimers: vi.advanceTimersByTime });
      const onChange = vi.fn();
      render(<MatterNameInput value="" onChange={onChange} />);

      const input = screen.getByRole('textbox');
      await user.type(input, 'Test');

      // Fast-forward past debounce delay
      await act(async () => {
        vi.advanceTimersByTime(300);
      });

      await waitFor(() => {
        expect(onChange).toHaveBeenCalled();
      });
    });

    it('calls onChange immediately on blur', async () => {
      const user = userEvent.setup({ advanceTimers: vi.advanceTimersByTime });
      const onChange = vi.fn();
      render(<MatterNameInput value="" onChange={onChange} />);

      const input = screen.getByRole('textbox');
      await user.type(input, 'Test');

      // Blur without waiting for debounce
      await act(async () => {
        input.blur();
      });

      // Should call onChange immediately on blur without waiting for debounce
      expect(onChange).toHaveBeenCalledWith('Test');
    });

    it('syncs value when prop changes', async () => {
      const { rerender } = render(<MatterNameInput value="Initial" onChange={vi.fn()} />);

      expect(screen.getByRole('textbox')).toHaveValue('Initial');

      rerender(<MatterNameInput value="Updated" onChange={vi.fn()} />);

      expect(screen.getByRole('textbox')).toHaveValue('Updated');
    });
  });

  describe('validation', () => {
    it('shows error for empty name after blur', async () => {
      const user = userEvent.setup({ advanceTimers: vi.advanceTimersByTime });
      const onChange = vi.fn();
      render(<MatterNameInput value="Test" onChange={onChange} />);

      const input = screen.getByRole('textbox');
      await user.clear(input);

      // Blur to trigger validation
      await act(async () => {
        input.blur();
      });

      await waitFor(() => {
        expect(screen.getByText(/matter name is required/i)).toBeInTheDocument();
      });
    });

    it('shows error when exceeding max length', async () => {
      const user = userEvent.setup({ advanceTimers: vi.advanceTimersByTime });
      const onChange = vi.fn();
      render(<MatterNameInput value="" onChange={onChange} />);

      const input = screen.getByRole('textbox');
      const longName = 'a'.repeat(101);
      await user.type(input, longName);

      // Over-limit shows error immediately during typing
      await act(async () => {
        vi.advanceTimersByTime(300);
      });

      await waitFor(() => {
        expect(screen.getByText(/must be 100 characters or less/i)).toBeInTheDocument();
      });
    });

    it('character count shows over limit in error style', async () => {
      const user = userEvent.setup({ advanceTimers: vi.advanceTimersByTime });
      render(<MatterNameInput value="" onChange={vi.fn()} />);

      const input = screen.getByRole('textbox');
      const longName = 'a'.repeat(101);
      await user.type(input, longName);

      await act(async () => {
        vi.advanceTimersByTime(300);
      });

      expect(screen.getByText('101/100')).toBeInTheDocument();
    });

    it('does not show error for valid name before blur', async () => {
      const user = userEvent.setup({ advanceTimers: vi.advanceTimersByTime });
      render(<MatterNameInput value="" onChange={vi.fn()} />);

      const input = screen.getByRole('textbox');
      await user.type(input, 'Valid Name');

      await act(async () => {
        vi.advanceTimersByTime(300);
      });

      // No error should show before blur for valid input
      await waitFor(() => {
        expect(screen.queryByRole('alert')).not.toBeInTheDocument();
      });
    });

    it('exactly 100 chars is valid', async () => {
      const user = userEvent.setup({ advanceTimers: vi.advanceTimersByTime });
      render(<MatterNameInput value="" onChange={vi.fn()} />);

      const input = screen.getByRole('textbox');
      const maxName = 'a'.repeat(100);
      await user.type(input, maxName);

      await act(async () => {
        vi.advanceTimersByTime(300);
      });

      await waitFor(() => {
        expect(screen.queryByText(/must be 100 characters or less/i)).not.toBeInTheDocument();
      });
    });

    it('validates on blur even without prior typing', async () => {
      const onChange = vi.fn();
      render(<MatterNameInput value="" onChange={onChange} />);

      const input = screen.getByRole('textbox');

      // Just focus and blur without typing
      await act(async () => {
        input.focus();
        input.blur();
      });

      await waitFor(() => {
        expect(screen.getByText(/matter name is required/i)).toBeInTheDocument();
      });
    });
  });

  describe('accessibility', () => {
    it('input has proper label association', () => {
      render(<MatterNameInput value="" onChange={vi.fn()} />);

      const input = screen.getByLabelText(/matter name/i);
      expect(input).toBeInTheDocument();
    });

    it('input has aria-invalid when error present', async () => {
      const user = userEvent.setup({ advanceTimers: vi.advanceTimersByTime });
      render(<MatterNameInput value="Test" onChange={vi.fn()} />);

      const input = screen.getByRole('textbox');
      await user.clear(input);

      // Blur to trigger validation
      await act(async () => {
        input.blur();
      });

      await waitFor(() => {
        expect(input).toHaveAttribute('aria-invalid', 'true');
      });
    });

    it('error message has alert role', async () => {
      const user = userEvent.setup({ advanceTimers: vi.advanceTimersByTime });
      render(<MatterNameInput value="Test" onChange={vi.fn()} />);

      const input = screen.getByRole('textbox');
      await user.clear(input);

      await act(async () => {
        input.blur();
      });

      await waitFor(() => {
        expect(screen.getByRole('alert')).toBeInTheDocument();
      });
    });

    it('input has aria-describedby linking to hint', () => {
      render(<MatterNameInput value="Test" onChange={vi.fn()} isAutoGenerated={true} />);

      const input = screen.getByRole('textbox');
      expect(input).toHaveAttribute('aria-describedby', 'matter-name-hint');
    });

    it('input has aria-describedby linking to error when invalid', async () => {
      const user = userEvent.setup({ advanceTimers: vi.advanceTimersByTime });
      render(<MatterNameInput value="Test" onChange={vi.fn()} />);

      const input = screen.getByRole('textbox');
      await user.clear(input);

      await act(async () => {
        input.blur();
      });

      await waitFor(() => {
        expect(input).toHaveAttribute('aria-describedby', 'matter-name-error');
      });
    });
  });

  describe('custom className', () => {
    it('applies custom className to wrapper', () => {
      const { container } = render(
        <MatterNameInput value="" onChange={vi.fn()} className="custom-class" />
      );

      expect(container.firstChild).toHaveClass('custom-class');
    });
  });
});
