'use client';

import { useEffect, useRef, useState } from 'react';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { cn } from '@/lib/utils';

/**
 * MatterNameInput Component
 *
 * Editable matter name input with auto-generation note and validation.
 * Maximum 100 characters.
 */

/** Maximum characters for matter name */
const MAX_NAME_LENGTH = 100;

/** Debounce delay for validation (ms) */
const DEBOUNCE_DELAY = 300;

interface MatterNameInputProps {
  /** Current matter name value */
  value: string;
  /** Callback when name changes */
  onChange: (name: string) => void;
  /** Whether the name was auto-generated (shows helper text) */
  isAutoGenerated?: boolean;
  /** Optional className */
  className?: string;
}

export function MatterNameInput({
  value,
  onChange,
  isAutoGenerated = true,
  className,
}: MatterNameInputProps) {
  const [localValue, setLocalValue] = useState(value);
  const [error, setError] = useState<string | null>(null);
  const debounceRef = useRef<ReturnType<typeof setTimeout> | null>(null);

  // Sync local value when prop changes (e.g., auto-generation)
  useEffect(() => {
    setLocalValue(value);
  }, [value]);

  const validateName = (name: string): string | null => {
    const trimmed = name.trim();
    if (trimmed.length === 0) {
      return 'Matter name is required';
    }
    if (trimmed.length > MAX_NAME_LENGTH) {
      return `Matter name must be ${MAX_NAME_LENGTH} characters or less`;
    }
    return null;
  };

  const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const newValue = e.target.value;
    setLocalValue(newValue);

    // Clear any pending debounce
    if (debounceRef.current) {
      clearTimeout(debounceRef.current);
    }

    // Debounce the validation and onChange callback
    debounceRef.current = setTimeout(() => {
      const validationError = validateName(newValue);
      setError(validationError);

      // Only call onChange if valid or empty (let parent handle required validation)
      onChange(newValue);
    }, DEBOUNCE_DELAY);
  };

  // Cleanup debounce on unmount
  useEffect(() => {
    return () => {
      if (debounceRef.current) {
        clearTimeout(debounceRef.current);
      }
    };
  }, []);

  const charCount = localValue.length;
  const isOverLimit = charCount > MAX_NAME_LENGTH;

  return (
    <div className={cn('space-y-2', className)}>
      <Label htmlFor="matter-name">Matter Name</Label>
      <div className="relative">
        <Input
          id="matter-name"
          type="text"
          value={localValue}
          onChange={handleChange}
          placeholder="Enter matter name"
          aria-invalid={!!error}
          aria-describedby={error ? 'matter-name-error' : 'matter-name-hint'}
          className={cn(
            'pr-16',
            error && 'border-destructive focus-visible:border-destructive focus-visible:ring-destructive/50'
          )}
        />
        <span
          className={cn(
            'absolute right-3 top-1/2 -translate-y-1/2 text-xs',
            isOverLimit ? 'text-destructive' : 'text-muted-foreground'
          )}
        >
          {charCount}/{MAX_NAME_LENGTH}
        </span>
      </div>

      {/* Helper text or error */}
      {error ? (
        <p id="matter-name-error" className="text-sm text-destructive" role="alert">
          {error}
        </p>
      ) : isAutoGenerated ? (
        <p id="matter-name-hint" className="text-sm text-muted-foreground">
          Auto-generated from first file &mdash; click to edit
        </p>
      ) : null}
    </div>
  );
}
