'use client';

import { useState, useCallback } from 'react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { ArrowLeft, Loader2 } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { FileDropZone } from './FileDropZone';
import { FileReviewList } from './FileReviewList';
import { MatterNameInput } from './MatterNameInput';
import { ActDiscoveryModal } from './ActDiscoveryModal';
import {
  useUploadWizardStore,
  selectCanStartUpload,
  selectFileCount,
} from '@/stores/uploadWizardStore';
import type { DetectedAct } from '@/types/upload';

/**
 * UploadWizard Component
 *
 * Main container for the multi-stage upload flow.
 * Stages: FILE_SELECTION → REVIEW → ACT_DISCOVERY → (hand off to upload progress)
 *
 * Per ADR-005: Act Discovery is shown before final upload begins.
 */

/** Mock data for Act Discovery (MVP - backend not yet available) */
const MOCK_DETECTED_ACTS: DetectedAct[] = [
  {
    id: 'act-1',
    actName: 'Securities Act, 1992',
    citationCount: 5,
    status: 'found',
    sourceFile: 'Annexure_P3.pdf',
  },
  {
    id: 'act-2',
    actName: 'SARFAESI Act, 2002',
    citationCount: 3,
    status: 'found',
    sourceFile: 'Annexure_K.pdf',
  },
  {
    id: 'act-3',
    actName: 'BNS Act, 2023',
    citationCount: 12,
    status: 'missing',
  },
  {
    id: 'act-4',
    actName: 'Negotiable Instruments Act',
    citationCount: 8,
    status: 'missing',
  },
  {
    id: 'act-5',
    actName: 'DRT Act, 1993',
    citationCount: 4,
    status: 'missing',
  },
  {
    id: 'act-6',
    actName: 'Companies Act, 2013',
    citationCount: 2,
    status: 'missing',
  },
];

export function UploadWizard() {
  const router = useRouter();

  // Store state (using selector pattern)
  const currentStage = useUploadWizardStore((state) => state.currentStage);
  const files = useUploadWizardStore((state) => state.files);
  const matterName = useUploadWizardStore((state) => state.matterName);
  const isLoading = useUploadWizardStore((state) => state.isLoading);
  const detectedActs = useUploadWizardStore((state) => state.detectedActs);
  const canStartUpload = useUploadWizardStore(selectCanStartUpload);
  const fileCount = useUploadWizardStore(selectFileCount);

  // Store actions
  const addFiles = useUploadWizardStore((state) => state.addFiles);
  const removeFile = useUploadWizardStore((state) => state.removeFile);
  const setMatterName = useUploadWizardStore((state) => state.setMatterName);
  const setDetectedActs = useUploadWizardStore((state) => state.setDetectedActs);
  const setStage = useUploadWizardStore((state) => state.setStage);
  const startUpload = useUploadWizardStore((state) => state.startUpload);
  const reset = useUploadWizardStore((state) => state.reset);

  // Local state for act discovery modal
  const [isActModalOpen, setIsActModalOpen] = useState(false);
  const [hasSeenActModal, setHasSeenActModal] = useState(false);

  // Track if matter name has been manually edited
  const [isNameAutoGenerated, setIsNameAutoGenerated] = useState(true);

  const handleFilesSelected = useCallback(
    (selectedFiles: File[]) => {
      addFiles(selectedFiles);
      setIsNameAutoGenerated(true);
    },
    [addFiles]
  );

  const handleMatterNameChange = useCallback(
    (name: string) => {
      setMatterName(name);
      setIsNameAutoGenerated(false);
    },
    [setMatterName]
  );

  const handleStartProcessing = useCallback(() => {
    // For MVP: Show mock Act Discovery modal if not already seen
    if (!hasSeenActModal && fileCount > 0) {
      setDetectedActs(MOCK_DETECTED_ACTS);
      setIsActModalOpen(true);
      setStage('ACT_DISCOVERY');
      return;
    }

    // Start upload process and navigate to stage 3-4 (Story 9-5)
    startUpload();
    // For MVP: Navigate to placeholder or future upload progress page
    // The actual upload progress will be implemented in Story 9-5
    router.push('/upload/processing');
  }, [hasSeenActModal, fileCount, setDetectedActs, setStage, startUpload, router]);

  const handleActModalClose = useCallback(() => {
    setIsActModalOpen(false);
    setHasSeenActModal(true);
    setStage('REVIEW');
  }, [setStage]);

  const handleUploadMissingActs = useCallback(
    (actFiles: File[]) => {
      // For MVP: Just add to files list as reference material
      addFiles(actFiles);
    },
    [addFiles]
  );

  const handleActModalContinue = useCallback(() => {
    setIsActModalOpen(false);
    setHasSeenActModal(true);
    // Start actual upload
    startUpload();
    router.push('/upload/processing');
  }, [startUpload, router]);

  const handleActModalSkip = useCallback(() => {
    setIsActModalOpen(false);
    setHasSeenActModal(true);
    setStage('REVIEW');
  }, [setStage]);

  const handleCancel = useCallback(() => {
    reset();
    router.push('/');
  }, [reset, router]);

  return (
    <div className="min-h-screen bg-background">
      {/* Header with back navigation */}
      <header className="border-b">
        <div className="container mx-auto px-4 py-4">
          <Link
            href="/"
            className="inline-flex items-center gap-2 text-muted-foreground hover:text-foreground transition-colors"
          >
            <ArrowLeft className="size-4" />
            Back to Dashboard
          </Link>
        </div>
      </header>

      {/* Main content */}
      <main className="container mx-auto px-4 py-8 max-w-2xl">
        <h1 className="text-2xl font-bold text-center mb-8">Create New Matter</h1>

        {/* Stage 1: File Selection */}
        {currentStage === 'FILE_SELECTION' && (
          <FileDropZone onFilesSelected={handleFilesSelected} />
        )}

        {/* Stage 2: Review & Name */}
        {(currentStage === 'REVIEW' || currentStage === 'ACT_DISCOVERY') && (
          <div className="space-y-6">
            {/* Matter Name Input */}
            <MatterNameInput
              value={matterName}
              onChange={handleMatterNameChange}
              isAutoGenerated={isNameAutoGenerated}
            />

            {/* File Review List */}
            <FileReviewList
              files={files}
              onRemoveFile={removeFile}
              onAddFiles={handleFilesSelected}
            />

            {/* Action Buttons */}
            <div className="flex justify-end gap-3 pt-4">
              <Button variant="outline" onClick={handleCancel}>
                Cancel
              </Button>
              <Button
                onClick={handleStartProcessing}
                disabled={!canStartUpload || isLoading}
              >
                {isLoading ? (
                  <>
                    <Loader2 className="size-4 mr-2 animate-spin" />
                    Processing...
                  </>
                ) : (
                  'Start Processing'
                )}
              </Button>
            </div>
          </div>
        )}

        {/* Stage 2.5: Act Discovery Modal */}
        <ActDiscoveryModal
          isOpen={isActModalOpen}
          onClose={handleActModalClose}
          detectedActs={detectedActs}
          onUploadMissingActs={handleUploadMissingActs}
          onContinue={handleActModalContinue}
          onSkip={handleActModalSkip}
        />
      </main>
    </div>
  );
}
