'use client';

import { useState, useCallback } from 'react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { AlertCircle, ArrowLeft, Loader2, X } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { FileDropZone } from './FileDropZone';
import { FileReviewList } from './FileReviewList';
import { MatterNameInput } from './MatterNameInput';
import { ActDiscoveryModal } from './ActDiscoveryModal';
import {
  useUploadWizardStore,
  selectCanStartUpload,
  selectFileCount,
} from '@/stores/uploadWizardStore';
import type { DetectedAct } from '@/types/upload';

/**
 * UploadWizard Component
 *
 * Main container for the multi-stage upload flow.
 * Stages: FILE_SELECTION → REVIEW → ACT_DISCOVERY → (hand off to upload progress)
 *
 * Per ADR-005: Act Discovery is shown before final upload begins.
 *
 * NOTE: Act Discovery modal is currently disabled pending backend integration.
 * The modal will be re-enabled once the Act Detection API (Epic 3) is available.
 */

// Act Discovery is disabled until backend integration is complete
// Set to true only in development mode with explicit env flag
const ENABLE_ACT_DISCOVERY_MOCK =
  process.env.NODE_ENV === 'development' &&
  process.env.NEXT_PUBLIC_ENABLE_ACT_DISCOVERY_MOCK === 'true';

export function UploadWizard() {
  const router = useRouter();

  // Store state (using selector pattern)
  const currentStage = useUploadWizardStore((state) => state.currentStage);
  const files = useUploadWizardStore((state) => state.files);
  const matterName = useUploadWizardStore((state) => state.matterName);
  const isLoading = useUploadWizardStore((state) => state.isLoading);
  const error = useUploadWizardStore((state) => state.error);
  const detectedActs = useUploadWizardStore((state) => state.detectedActs);
  const canStartUpload = useUploadWizardStore(selectCanStartUpload);
  const fileCount = useUploadWizardStore(selectFileCount);

  // Store actions
  const addFiles = useUploadWizardStore((state) => state.addFiles);
  const removeFile = useUploadWizardStore((state) => state.removeFile);
  const setMatterName = useUploadWizardStore((state) => state.setMatterName);
  const setDetectedActs = useUploadWizardStore((state) => state.setDetectedActs);
  const setStage = useUploadWizardStore((state) => state.setStage);
  const startUpload = useUploadWizardStore((state) => state.startUpload);
  const setError = useUploadWizardStore((state) => state.setError);
  const reset = useUploadWizardStore((state) => state.reset);

  // Local state for act discovery modal
  const [isActModalOpen, setIsActModalOpen] = useState(false);
  const [hasSeenActModal, setHasSeenActModal] = useState(false);

  // Track if matter name has been manually edited
  const [isNameAutoGenerated, setIsNameAutoGenerated] = useState(true);

  const handleFilesSelected = useCallback(
    (selectedFiles: File[]) => {
      addFiles(selectedFiles);
      setIsNameAutoGenerated(true);
    },
    [addFiles]
  );

  const handleMatterNameChange = useCallback(
    (name: string) => {
      setMatterName(name);
      setIsNameAutoGenerated(false);
    },
    [setMatterName]
  );

  const handleStartProcessing = useCallback(() => {
    // Act Discovery is disabled in production - only show with explicit dev flag (H1 fix)
    // This prevents showing fake "Securities Act, 1992" to users uploading real documents
    // Re-enable once Epic 3 Act Detection API is integrated
    if (ENABLE_ACT_DISCOVERY_MOCK && !hasSeenActModal && fileCount > 0) {
      // Mock detected acts for development only
      const mockActs: DetectedAct[] = [
        { id: 'act-1', actName: 'Mock Act (Dev Only)', citationCount: 1, status: 'missing' },
      ];
      setDetectedActs(mockActs);
      setIsActModalOpen(true);
      setStage('ACT_DISCOVERY');
      return;
    }

    // Start upload process and navigate to stage 3-4 (Story 9-5)
    startUpload();
    // For MVP: Navigate to placeholder or future upload progress page
    // The actual upload progress will be implemented in Story 9-5
    router.push('/upload/processing');
  }, [hasSeenActModal, fileCount, setDetectedActs, setStage, startUpload, router]);

  const handleActModalClose = useCallback(() => {
    setIsActModalOpen(false);
    setHasSeenActModal(true);
    setStage('REVIEW');
  }, [setStage]);

  const handleUploadMissingActs = useCallback(
    (actFiles: File[]) => {
      // For MVP: Just add to files list as reference material
      addFiles(actFiles);
    },
    [addFiles]
  );

  const handleActModalContinue = useCallback(() => {
    setIsActModalOpen(false);
    setHasSeenActModal(true);
    // Start actual upload
    startUpload();
    router.push('/upload/processing');
  }, [startUpload, router]);

  const handleActModalSkip = useCallback(() => {
    setIsActModalOpen(false);
    setHasSeenActModal(true);
    setStage('REVIEW');
  }, [setStage]);

  const handleCancel = useCallback(() => {
    reset();
    router.push('/');
  }, [reset, router]);

  const handleDismissError = useCallback(() => {
    setError(null);
  }, [setError]);

  return (
    <div className="min-h-screen bg-background" data-testid="upload-wizard">
      {/* Header with back navigation */}
      <header className="border-b" data-testid="upload-wizard-header">
        <div className="container mx-auto px-4 py-4">
          <Link
            href="/"
            className="inline-flex items-center gap-2 text-muted-foreground hover:text-foreground transition-colors"
          >
            <ArrowLeft className="size-4" />
            Back to Dashboard
          </Link>
        </div>
      </header>

      {/* Main content */}
      <main className="container mx-auto px-4 py-8 max-w-2xl">
        <h1 className="text-2xl font-bold text-center mb-8">Create New Matter</h1>

        {/* Error Alert */}
        {error && (
          <div
            role="alert"
            className="mb-6 flex items-center gap-3 p-4 rounded-md bg-destructive/10 border border-destructive/20 text-destructive"
            data-testid="upload-wizard-error"
          >
            <AlertCircle className="size-5 flex-shrink-0" />
            <span className="flex-1 text-sm">{error}</span>
            <Button
              variant="ghost"
              size="icon"
              className="size-6 text-destructive hover:text-destructive hover:bg-destructive/20"
              onClick={handleDismissError}
              aria-label="Dismiss error"
            >
              <X className="size-4" />
            </Button>
          </div>
        )}

        {/* Stage 1: File Selection */}
        {currentStage === 'FILE_SELECTION' && (
          <FileDropZone onFilesSelected={handleFilesSelected} />
        )}

        {/* Stage 2: Review & Name */}
        {(currentStage === 'REVIEW' || currentStage === 'ACT_DISCOVERY') && (
          <div className="space-y-6">
            {/* Matter Name Input */}
            <MatterNameInput
              value={matterName}
              onChange={handleMatterNameChange}
              isAutoGenerated={isNameAutoGenerated}
            />

            {/* File Review List */}
            <FileReviewList
              files={files}
              onRemoveFile={removeFile}
              onAddFiles={handleFilesSelected}
            />

            {/* Action Buttons */}
            <div className="flex justify-end gap-3 pt-4">
              <Button variant="outline" onClick={handleCancel} data-testid="upload-wizard-cancel-button">
                Cancel
              </Button>
              <Button
                onClick={handleStartProcessing}
                disabled={!canStartUpload || isLoading}
                data-testid="upload-wizard-start-button"
              >
                {isLoading ? (
                  <>
                    <Loader2 className="size-4 mr-2 animate-spin" />
                    Processing...
                  </>
                ) : (
                  'Start Processing'
                )}
              </Button>
            </div>
          </div>
        )}

        {/* Stage 2.5: Act Discovery Modal */}
        <ActDiscoveryModal
          isOpen={isActModalOpen}
          onClose={handleActModalClose}
          detectedActs={detectedActs}
          onUploadMissingActs={handleUploadMissingActs}
          onContinue={handleActModalContinue}
          onSkip={handleActModalSkip}
        />
      </main>
    </div>
  );
}
