-- Add missing job types to processing_jobs constraint
-- Fixes: EVENT_CLASSIFICATION, ENTITY_LINKING, CITATION_EXTRACTION,
--        CITATION_VERIFICATION, CONTRADICTION_DETECTION, DATE_EXTRACTION, ANOMALY_DETECTION

-- Drop the old constraint
ALTER TABLE public.processing_jobs
DROP CONSTRAINT IF EXISTS processing_jobs_job_type_check;

-- Add updated constraint with all job types
ALTER TABLE public.processing_jobs
ADD CONSTRAINT processing_jobs_job_type_check
CHECK (job_type IN (
  -- Original types
  'DOCUMENT_PROCESSING',
  'OCR',
  'VALIDATION',
  'CHUNKING',
  'EMBEDDING',
  'ENTITY_EXTRACTION',
  'ALIAS_RESOLUTION',
  -- New types added for timeline and citations
  'CITATION_EXTRACTION',
  'CITATION_VERIFICATION',
  'CONTRADICTION_DETECTION',
  'DATE_EXTRACTION',
  'EVENT_CLASSIFICATION',
  'ENTITY_LINKING',
  'ANOMALY_DETECTION'
));

-- Update comment to reflect all types
COMMENT ON COLUMN public.processing_jobs.job_type IS 'Type: DOCUMENT_PROCESSING, OCR, VALIDATION, CHUNKING, EMBEDDING, ENTITY_EXTRACTION, ALIAS_RESOLUTION, CITATION_EXTRACTION, CITATION_VERIFICATION, CONTRADICTION_DETECTION, DATE_EXTRACTION, EVENT_CLASSIFICATION, ENTITY_LINKING, ANOMALY_DETECTION';
